# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/subpop/go-ini
%global goipath         github.com/subpop/go-ini
Version:                0.1.5

%gometa -L -f

%global common_description %{expand:
Go package that encodes and decodes INI-files.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           golang-github-subpop-ini
Release:        %autorelease
Summary:        Go package that encodes and decodes INI-files

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
